name: saferoad
description: Sistema de Seguridad Vial Inteligente

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.1
  cloud_firestore: ^4.8.4
  firebase_storage: ^11.3.1
  firebase_messaging: ^14.7.1
  firebase_functions: ^4.3.1
  google_maps_flutter: ^2.2.6
  google_places_flutter: ^1.0.1
  geolocator: ^11.0.1
  image_picker: ^1.0.4
  http: ^1.1.0
  mercadopago_sdk: ^2.1.0
  provider: ^6.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true