// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEfsrrAlvv40aar35aEdUNl0ye55U5lpc',
    appId: '1:299074642880:web:e2708b6978c3b3f4a19e25',
    messagingSenderId: '299074642880',
    projectId: 'saferoad-674e8',
    authDomain: 'saferoad-674e8.firebaseapp.com',
    storageBucket: 'saferoad-674e8.firebasestorage.app',
    measurementId: 'G-RQ5VQ1QC7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6CTqclTOedvgeneHDaF4YsETnS2uvY2Y',
    appId: '1:299074642880:android:345cc9690fe3cf48a19e25',
    messagingSenderId: '299074642880',
    projectId: 'saferoad-674e8',
    storageBucket: 'saferoad-674e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCEKHfOLdO8LdwPx3CsIK-3dcO8FhwVzc',
    appId: '1:299074642880:ios:ab146bc6e6f4c3f2a19e25',
    messagingSenderId: '299074642880',
    projectId: 'saferoad-674e8',
    storageBucket: 'saferoad-674e8.firebasestorage.app',
    iosBundleId: 'com.example.saferoad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCEKHfOLdO8LdwPx3CsIK-3dcO8FhwVzc',
    appId: '1:299074642880:ios:ab146bc6e6f4c3f2a19e25',
    messagingSenderId: '299074642880',
    projectId: 'saferoad-674e8',
    storageBucket: 'saferoad-674e8.firebasestorage.app',
    iosBundleId: 'com.example.saferoad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEfsrrAlvv40aar35aEdUNl0ye55U5lpc',
    appId: '1:299074642880:web:113761ccc855d40ba19e25',
    messagingSenderId: '299074642880',
    projectId: 'saferoad-674e8',
    authDomain: 'saferoad-674e8.firebaseapp.com',
    storageBucket: 'saferoad-674e8.firebasestorage.app',
    measurementId: 'G-5LRD0930B3',
  );
}
